//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFAgileStrategy.Client.AgileEmployeeServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.MyWCFVersioningExample.com/sample/2016/08")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.MyWCFVersioningExample.com/sample/2016/08", ConfigurationName="AgileEmployeeServiceProxy.EmployeeService")]
    public interface EmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee UpdateEmployee(WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        System.Threading.Tasks.Task<WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee> UpdateEmployeeAsync(WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceChannel : WCFAgileStrategy.Client.AgileEmployeeServiceProxy.EmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WCFAgileStrategy.Client.AgileEmployeeServiceProxy.EmployeeService>, WCFAgileStrategy.Client.AgileEmployeeServiceProxy.EmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee UpdateEmployee(WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee emp) {
            return base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee> UpdateEmployeeAsync(WCFAgileStrategy.Client.AgileEmployeeServiceProxy.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
    }
}
