//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.MyWCFVersioningExample.com/sample/2016/08", ConfigurationName="EmployeeServiceProxy.EmployeeService")]
    public interface EmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        Models.Employee UpdateEmployee(Models.Employee emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        System.Threading.Tasks.Task<Models.Employee> UpdateEmployeeAsync(Models.Employee emp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceChannel : WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService>, WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Models.Employee UpdateEmployee(Models.Employee emp) {
            return base.Channel.UpdateEmployee(emp);
        }
        
        public System.Threading.Tasks.Task<Models.Employee> UpdateEmployeeAsync(Models.Employee emp) {
            return base.Channel.UpdateEmployeeAsync(emp);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="EmployeeService", Namespace="http://www.MyWCFVersioningExample.com/sample/2016/09", ConfigurationName="EmployeeServiceProxy.EmployeeService1")]
    public interface EmployeeService1 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.MyWCFVersioningExample.com/sample/2016/08) of message UpdateEmployeeRequest does not match the default value (http://www.MyWCFVersioningExample.com/sample/2016/09)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse UpdateEmployee(WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "ee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/08/EmployeeService/UpdateEmploy" +
            "eeResponse")]
        System.Threading.Tasks.Task<WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse> UpdateEmployeeAsync(WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/09/EmployeeService/GetEmployee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/09/EmployeeService/GetEmployeeR" +
            "esponse")]
        Models.Employee GetEmployee(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.MyWCFVersioningExample.com/sample/2016/09/EmployeeService/GetEmployee", ReplyAction="http://www.MyWCFVersioningExample.com/sample/2016/09/EmployeeService/GetEmployeeR" +
            "esponse")]
        System.Threading.Tasks.Task<Models.Employee> GetEmployeeAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployee", WrapperNamespace="http://www.MyWCFVersioningExample.com/sample/2016/08", IsWrapped=true)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.MyWCFVersioningExample.com/sample/2016/08", Order=0)]
        public Models.Employee emp;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(Models.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateEmployeeResponse", WrapperNamespace="http://www.MyWCFVersioningExample.com/sample/2016/08", IsWrapped=true)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.MyWCFVersioningExample.com/sample/2016/08", Order=0)]
        public Models.Employee UpdateEmployeeResult;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(Models.Employee UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeService1Channel : WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeService1Client : System.ServiceModel.ClientBase<WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1>, WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1 {
        
        public EmployeeService1Client() {
        }
        
        public EmployeeService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1.UpdateEmployee(WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public Models.Employee UpdateEmployee(Models.Employee emp) {
            WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest inValue = new WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest();
            inValue.emp = emp;
            WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse retVal = ((WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1)(this)).UpdateEmployee(inValue);
            return retVal.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse> WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1.UpdateEmployeeAsync(WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeResponse> UpdateEmployeeAsync(Models.Employee emp) {
            WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest inValue = new WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.UpdateEmployeeRequest();
            inValue.emp = emp;
            return ((WCFSemiStrictStrategy.ClientV1.EmployeeServiceProxy.EmployeeService1)(this)).UpdateEmployeeAsync(inValue);
        }
        
        public Models.Employee GetEmployee(int id) {
            return base.Channel.GetEmployee(id);
        }
        
        public System.Threading.Tasks.Task<Models.Employee> GetEmployeeAsync(int id) {
            return base.Channel.GetEmployeeAsync(id);
        }
    }
}
